make client threadsafe
ClickHouse/clickhouse-cpp pull request #122
Opened 2021-12-03 04:14 UTC by caiowakamatsuahrefs

closes #37

2021-12-03 04:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=122) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=122) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-cpp?pullRequest=122) it.</sub>

2022-01-07 02:04 UTC, caiowakamatsuahrefs commented
@Enmk @Vertver @traceon ping

2022-01-18 15:39 UTC, Enmk requested changes
IMO it is best to create a thread-safe wrapper around `Client` rather than making it a thread-safe by-deafult. That would allow users to choose between thread-safe and non-thread-safe-but-more-performant APIs.

2022-01-19 20:31 UTC, filimonov commented
+1. Saying that it's threadsafe when actually only a single thread can work with it (and others simply wait for locks) - sounds unfair. I would just add to documentation that client is single threaded and not thread-safe.

2022-02-02 15:45 UTC, closed without merging