Add list of hosts with ports for setting connection
ClickHouse/clickhouse-cpp pull request #139
Opened 2022-01-11 17:21 UTC by DF5HSE

`SetHost` can take `std::vector` of `ClientOptions::HostPort` structures, that contains host name and optionally port number. If `HostPort.port` is `nullopt`, then port from `SetPort` (or default port if `SetPort` wasn't called) is used.

When `ResetConnection` is called, it tries to connect to the first host. If connection failed, then it tries to connect to the next host in list, while list doesn't end up. If list ends up, `ResetConnection` throws exception of last host.

2022-01-11 17:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=139) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=139) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-cpp?pullRequest=139) it.</sub>

2022-01-19 21:38 UTC, PolyProgrammist commented
Looks good to me. I think it's better to merge commits in one. And providing more information about the reasons for commit (fault tolerance) and about the implementation (round robin) in pull request description would be great

2022-01-20 10:16 UTC, filimonov commented
The idea/motivation is clean. Maybe it would be clearer to push that logic a bit deeper?

Here we have iteration through different IPs which can be extracted from the same name:
https://github.com/ClickHouse/clickhouse-cpp/blob/b36c87fb6f09376f71fbda671cae4c754afc7ea4/clickhouse/base/socket.cpp#L87-L88

Maybe we can generalize that code a bit for multiple hosts/ports cases instead of creating one more retry loop outside?

In that case, connect timeouts should work better.

2022-01-24 08:34 UTC, Enmk requested changes
Please add proper unit-tests and fix highlighted issues.

2022-01-24 08:34 UTC, Enmk commented on clickhouse/client.cpp
Please modify endpoints creation to simplify the `ResetConnection()`
```suggestion
ClientOptions modifyClientOptions(ClientOptions opts)
{
    if (!opts.host.empty())
        opts.endpoints.insert(opts.endpoints.begin(), ClientOptions::Endpoint{opts.host, opts.port});

    return opts;
}

Client::Impl::Impl(const ClientOptions& opts)
    : options_(modifyClientOptions(opts))
{
```

2022-01-24 08:34 UTC, Enmk commented on clickhouse/client.cpp
> +        const ClientOptions::HostPort& host_port = i == -1 ? ClientOptions::HostPort(options_.host) : options_.hosts_ports[i];
Please update the list of endpoints before copying it to a `options_` so you don't have to do this. (see above)

2022-01-24 08:34 UTC, Enmk commented on clickhouse/client.h
> +    const std::optional<ClientOptions::HostPort>& GetConnectedHostPort() const;
Please specify in comments when this function may return `nullopt`.

2022-01-24 08:39 UTC, Enmk commented on tests/simple/main.cpp
> +                              .SetPingBeforeQuery(true));
BTW, [this](https://github.com/ClickHouse/clickhouse-cpp/pull/139#discussion_r790474521) allows simplifying client code:
```suggestion
            ClientOptions::Endpoint correct_endpoint{"localhost", 9000};
            Client client(ClientOptions()
                              .SetEndpoints({
                                           {"localhost", 8000}, // wrong port
                                           {"localhost", 7000}, // wrong port
                                           {"1127.91.2.1"}, // wrong host
                                           {"1127.91.2.2"}, // wrong host
                                           {"notlocalwronghost"}, // wrong host
                                           {"another_notlocalwronghost"}, // wrong host
                                           {correct_endpoint},
                                           {"localhost", 9001}, // wrong port
                                           {"1127.911.2.2"}, // wrong host
                                       })
                              .SetPingBeforeQuery(true));
```

2022-01-24 08:46 UTC, Enmk requested changes
Please add proper unit-tests and fix highlighted issues.

2022-05-03 09:06 UTC, Enmk commented
@DF5HSE ping?

2022-05-03 10:11 UTC, PolyProgrammist commented
@Enmk hi, I have just started to continue working on this pr. Hope it will be ready soon

2023-04-19 08:29 UTC, closed without merging

2023-05-15 13:23 UTC, MikhailBurdukov commented
Hi! 
We think this feature will be very useful for us, so I would like to complete it. Can we reopen PR or is it better to open a new one?

2023-05-23 08:27 UTC, MikhailBurdukov commented
@Enmk ping?