Add options to use system abseil, lz4 and cityhash
ClickHouse/clickhouse-cpp pull request #168
Opened 2022-04-06 08:28 UTC by DavidKeller

This change solves #86, #99.

Furthermore, it eases Conan packaging, as Conan already provides abseil, lz4 and cityhash.

Signed-off-by: David Keller <david@woorton.com>

2022-04-11 12:04 UTC, DavidKeller commented
Hi,

CI is broken on master due to SSL error, hence I can't verify that my changes aren't causing regression.

See other MRs
- https://github.com/ClickHouse/clickhouse-cpp/actions/runs/2039802185
- https://github.com/ClickHouse/clickhouse-cpp/actions/runs/2042141964
- https://github.com/ClickHouse/clickhouse-cpp/actions/runs/2104298917

Would you be kind enough to have a look at the SSL issue ?

2022-04-11 12:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=168) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=168) before we can accept your contribution.<br/><hr/>**David Keller** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-cpp?pullRequest=168) it.</sub>

2022-04-12 16:32 UTC, filimonov commented
> Would you be kind enough to have a look at the SSL issue ?

Should be fixed in https://github.com/ClickHouse/clickhouse-cpp/pull/170 

BTW - maybe that should be also added to a build matrix? I.e. build with system libs, similar to

https://github.com/ClickHouse/clickhouse-cpp/blob/a85a9827792bb91642e0e4511e8083677f0c1b1e/.github/workflows/linux.yml#L40-L42

2022-04-13 07:50 UTC, Enmk commented on CMakeLists.txt
> +OPTION (USE_SYSTEM_CITYHASH "Use contrib cityhash" OFF)
```suggestion
OPTION (USE_SYSTEM_CITYHASH "Use system cityhash" OFF)
```

2022-04-13 07:54 UTC, Enmk commented
> BTW - maybe that should be also added to a build matrix? I.e. build with system libs, similar to

We DEFINITELY need to add at least 1 variant to the build matrix for each platform: build with system libs (i.e. `-DUSE_SYSTEM_CITYHASH=ON -DUSE_SYSTEM_ABSEIL=ON -DUSE_SYSTEM_LZ4=ON`)

2022-04-13 07:59 UTC, Enmk commented
@DavidKeller Tnak you for a PR, few more steps to get it merged:
* sign a CLA
* [update the build matrix](https://github.com/ClickHouse/clickhouse-cpp/pull/168#issuecomment-1097674784)
* Please also explain why would you need to move third-parties one level deeper? E.g. why `contrib/absl/absl` istead of just `contrib/absl`, etc?

2022-04-13 08:03 UTC, Enmk commented on CMakeLists.txt
> +OPTION (USE_SYSTEM_CITYHASH "Use contrib cityhash" OFF)
```suggestion
OPTION (WITH_SYSTEM_ABSEIL "Use system ABSEIL" OFF)
OPTION (WITH_SYSTEM_LZ4 "Use system LZ4" OFF)
OPTION (WITH_SYSTEM_CITYHASH "Use system cityhash" OFF)
```

To keep option names consistent.

2022-04-13 09:39 UTC, DavidKeller commented
>   * Please also explain why would you need to move third-parties one level deeper?
>   E.g. why `contrib/absl/absl` istead of just `contrib/absl`, etc?

In the previous layout, It user wants to use the contrib absl, the build system would have to include

```
    INCLUDE_DIRECTORIES (contrib)
```

But that would include other dependencies as well, even if the user prefers to rely on the system lz4 or cityhash.

The extra level allow to add only absl to the include path, i.e.:

```
    INCLUDE_DIRECTORIES (contrib/absl)
```

2022-04-13 10:20 UTC, DavidKeller commented
> We DEFINITELY need to add at least 1 variant to the build matrix for each platform: build with system libs

I've done this for linux & osx.

Regarding windows (mingw & msvc), it may be more tricky as:
- [lz4](https://community.chocolatey.org/packages?q=lz4), [cityhash](https://community.chocolatey.org/packages?q=cityhash) & [abseil](https://community.chocolatey.org/packages?q=absl), don't seem available on chocolatey
- [cityhash](https://packages.msys2.org/search?t=pkg&q=cityhash) don't seem available on msys2

2022-04-15 11:03 UTC, Enmk commented on CMakeLists.txt
> +OPTION (USE_SYSTEM_CITYHASH "Use system cityhash" OFF)
```suggestion
OPTION (WITH_SYSTEM_ABSEIL "Use system ABSEIL" OFF)
OPTION (WITH_SYSTEM_LZ4 "Use system LZ4" OFF)
OPTION (WITH_SYSTEM_CITYHASH "Use system cityhash" OFF)
```
To make option names consistent

2022-04-15 11:11 UTC, Enmk commented on .github/workflows/linux.yml
>        run: |
There seems to be a glitch in this multi-line value, maybe consider using `run: >-` instead of `run: |`. Not sure why it worked before...

2022-04-15 11:12 UTC, Enmk requested changes
Please fix the workflows, and it will be good to merge.

2022-04-21 10:31 UTC, DavidKeller commented
Gentlemen,

I've fought quite a bit in order to tests dependencies across all platforms.
Installing each dependency using platform's package manager when available was getting more and more complex.

So I've switched to conan, as it ease a lot the dependencies management.

**Pro**
- Having the clickhouse-client library within Conan Center would also ease adoption.
- A build using LLVM's libc++ has been added to the Linux matrix.

**Con**
- But this Conan work is not complete as demonstrated by the failing tests.
  When using Conan's LZ4 instead of contrib LZ4, checksum corruptions are detected. This is an important issue IMHO.

- Another issue is that system dependencies can't be used on windows due to a libtool/msvc bug (https://github.com/conan-io/conan-center-index/issues/9002)


I'm running out of time to solve these, but I'm pushing the current state to have your feeling on this work, I may resume later.

2022-05-03 08:19 UTC, Enmk commented
> I've fought quite a bit in order to test dependencies across all platforms. Installing each dependency using platform's package manager when available was getting more and more complex.
> 
> So I've switched to conan, as it eases dependencies management.

Ok, so could you please reduce the scope of this PR to just system-provided third-parties. I do believe that if it is hard to obtain a library on certain OS, then we can safely omit corresponding CI/CD job type. So you don't need to test system third-parties against all possible combinations, only for those that make sense.

Also, if possible, you may want to hard-code third-parties version installed to avoid accidental breakage in the future.

As for Conan: this is an interesting idea, but could we please move it to another PR?

2022-07-22 20:34 UTC, Enmk commented
@DavidKeller ping?

2022-07-26 14:11 UTC, DavidKeller commented
Hi, will try to split the MR and provide separate MR with conan by the end of the week.

2022-07-28 11:57 UTC, DavidKeller commented
Here is the current state:
- On `OSX` & `Win`, nothing has changed, the libary is still using the **builtin** dependencies.
- On `ubuntu-latest` (aka `ubuntu-20.04`), nothing has changed as well.
- A new `ubuntun-22.04` build has been created, which uses the **system** `abseil` & `lz4` and `gcc`.

Some remarks: 

1. It doesn't make sense to me to use **system** libraries with a different compiler (and `libstdc++`/`libc++`) than the one provided by the **system**, used to build these **system** libraries.
2.  Can't find a `cityhash` package (unmaintained since Ubuntu 13.0), but as `cityhash` is not a public dependency, I decided to rely on the builtin version, so the current build doesn't test the `WITH_SYSTEM_CITYHASH` switch :-(
  The alternative would be to build the `cityhash` package and install it locally prior the `clickhouse` build step.

What's your opinion on these remarks ?

2022-11-23 09:47 UTC, Enmk requested changes
Hi @DavidKeller sorry for a late reply. Looks nice, could you please resolve the merge issues?

2022-11-23 11:54 UTC, DavidKeller commented
Rebased.

2022-12-22 17:11 UTC, Jihadist commented
@Enmk sorry for ping. Are there any chances for this pr?

2022-12-28 21:41 UTC, Enmk commented
> @Enmk sorry for ping. Are there any chances for this pr?

Sure, just need to rebase and verify that it does what it advertizes.

2022-12-30 10:18 UTC, DavidKeller commented
> > @Enmk sorry for ping. Are there any chances for this pr?
> 
> Sure, just need to rebase and verify that it does what it advertizes.

We're no longer using clickhouse, so I'm afraid I won't spend more time rebasing it _again_.

@Jihadist, feel free to complete this MR.

I believe the power move here would be - once this get merged - to rely on conan to build everything and retrieve dependencies. See https://github.com/ClickHouse/clickhouse-cpp/commit/d34cd97263ae65e3b473ddb5827afee81fddd5b9

2022-12-31 11:59 UTC, Jihadist commented
@DavidKeller thank you for this pr and for conanfile especially. I'll try to continue your ideas. Looks like we do not need to rebase it again because no one changed cmake files since last rebasing.

2023-02-01 10:12 UTC, Enmk commented
Hi @DavidKeller  ! Thank you for your contribution, I think this is a good start for proper Conan support for clickhouse-cpp. Sorry if the review process wasn't smooth for you

2023-02-06 14:29 UTC, Jihadist commented
@Enmk this can be closed

2023-04-17 13:29 UTC, closed without merging