Separate building static and shared libs
ClickHouse/clickhouse-cpp pull request #219
Opened 2022-10-01 09:40 UTC by Jihadist

Introduce separating building static and shared libs, depends on cmake out-of-the-box option BUILD_SHARED_LIBS https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html. Also creates alias target for transparently linking to static or shared lib.

2022-10-01 09:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=219) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=219) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-cpp?pullRequest=219) it.</sub>

2022-10-03 11:59 UTC, Enmk requested changes
Hi, @Jihadist, thank you for contribution! Few notes:

- Please provide motivation for the change in PR description.
- It is not clear which version is now used in CI/CD testing, could you please add job to test both static and shared build?
- Any reason (besides final binary file name) to keep both targets:`clickhouse-cpp-lib-static` and `clickhouse-cpp-lib`? From my perspective, only one is going to be built every time. 

IMO, for static builds only, we'd better add an alias: `clickhouse-cpp-lib-static` (and also make sure that output binary name [stays `clickhouse-cpp-lib-static`](https://stackoverflow.com/a/45663205). Everywhere else just use a `clickhouse-cpp-lib`. This is not to break user's code.

2022-10-03 12:43 UTC, Jihadist commented
Ok, @Enmk 
- Reason: i wanna provide a conan recipe to conan-center-index for clickhouse-cpp. Conan does not support static and shared libs at the same time. Library should be build as static or as shared. 
- Ok, i'll try to figure out how to do that and change pr
- If project uses library with cmake FetchContent or as subdirectory project may depend on static target name. If we change target name for static libs it will be cmake error. There is only one reason why I do not change target name for static.

2022-10-04 12:57 UTC, Enmk commented
Regarding the CI/CD testing: IMO you might want to add another matrix parameter, [like here](https://github.com/ClickHouse/clickhouse-cpp/blob/master/.github/workflows/linux.yml#L17).
Something like:
```diff
      matrix:
        compiler: [clang-6, gcc-7, gcc-8, gcc-9]
        ssl: [ssl_ON, ssl_OFF]
+       build_type: [static, shared]
        include:
...
+       - build_type: shared
+         CMAKE_BUILD_TYPE_FLAG: -BUILD_SHARED_LIBS=ON
```

etc.

2022-10-04 12:58 UTC, Enmk commented
Also, if you wish to add that as a Conan module, please free to add any related CI/CD workflows

2022-10-04 13:22 UTC, Jihadist commented
> Regarding the CI/CD testing: IMO you might want to add another matrix parameter,

I did this but looks like windows shared build is broken

2022-10-14 21:24 UTC, Jihadist commented
If someone can help with windows shared build with export all, it will be nice

2022-10-16 13:54 UTC, 1261385937 commented
> If someone can help with windows shared build with export all, it will be nice

Addressed in #226

2022-10-16 13:54 UTC, 1261385937 commented
> If someone can help with windows shared build with export all, it will be nice

Addressed in #226

2022-10-17 12:21 UTC, Enmk commented
Another attempt to fix windows build here: #227 227

2023-02-01 10:10 UTC, Enmk approved these changes
LGTM

2023-02-01 10:10 UTC, merged