Fix abnormal column names in gcc7.3.1
ClickHouse/clickhouse-cpp pull request #317
Opened 2023-07-18 05:42 UTC by alenstarx

Fix abnormal column names in gcc7.3.1

example: "select 123,231,113"

on gcc7.3.1 output:
name:113, type:UInt8
name:113, type:UInt8
name:113, type:UInt8

on gcc9.3.1 output:
name:123, type:UInt8
name:231, type:UInt8
name:113, type:UInt8

2023-07-18 05:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-cpp?pullRequest=317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-cpp?pullRequest=317) it.</sub>

2023-07-20 13:39 UTC, Enmk requested changes
Looks good, but please add a test

2023-07-22 08:11 UTC, alenstarx commented
> Looks good, but please add a test

OK, Test has been added.

2023-07-28 12:26 UTC, Enmk commented on ut/client_ut.cpp
> +INSTANTIATE_TEST_SUITE_P(ColumnNames, AbnormalColumnNamesTest,
IMO it makes sense to move this test suite instantiation right to the definition of the test itself (`ut/abnormal_column_names_test.cpp`). That would make things a bit simpler.

2023-07-28 12:29 UTC, Enmk commented on ut/abnormal_column_names_test.h
> +class AbnormalColumnNamesTest : public testing::TestWithParam<
Please rename the test to something with `Client`, it is a convention that allows easy filtering out local tests vs tests that do requests to the server.

2023-07-28 12:30 UTC, Enmk commented on ut/abnormal_column_names_test.cpp
> +                std::cout << "query => " << query <<"\n" << PrettyPrintBlock{block};
It doesn't make sense to just print a block to STDOUT for CI/CD, nobody is going to manually verify the validity of the output. Please update the test to have `ASSERT_`/`EXPECT_` statements that actually check something.

2023-07-31 17:55 UTC, Enmk approved these changes
LGTM

2023-07-31 17:56 UTC, merged