Add ZSTD compression
ClickHouse/clickhouse-cpp pull request #367
Opened 2024-03-02 17:47 UTC by byian

To resolve #35 

- Added zstd v1.5.5 sources to contrib
- New cmake option WITH_SYSTEM_ZSTD to choose between building and using the system installed library
- Compression and decompression are implemented using the Simple API (so there is no choice of compression level)
- Updated tests

2024-03-04 11:14 UTC, byian commented
@Enmk Could you please trigger CI for this?

2024-03-07 12:54 UTC, Enmk commented on clickhouse/base/compressed.cpp
> +    }
defa
```suggestion
    }
    default:
        throw CompressionError("Unknown or unsupported compression method " + std::to_string((method)));
```

2024-03-12 15:15 UTC, Enmk requested changes
Some modifications required

2024-04-07 10:28 UTC, byian commented on clickhouse/base/compressed.cpp
> +    }
done

2024-04-07 10:28 UTC, byian commented on clickhouse/base/compressed.h
> +enum class CompressionMethodByte : uint8_t {
moved to cpp

2024-04-07 10:29 UTC, byian commented on clickhouse/client.h
> +#include "base/compressed.h"
done

2024-05-28 16:39 UTC, Enmk approved these changes
LGTM

2024-05-28 16:42 UTC, merged