Fixes to allow using absl::int128 as Int128
ClickHouse/clickhouse-cpp pull request #81
Opened 2021-03-23 15:31 UTC by Enmk

Fixed multiple compile-time issues using `absl::int128` as `clickhouse::Int128`

Added tests:
* Basic cases for Int128 numeric columns
* Parsing Decimal128 values from a string (basic and with overflow)

Known limitations:
* Overflow checks are broken for std::numeric_limits<Int128>::min() when there is no __int128.

2021-03-23 18:23 UTC, traceon requested changes
Left comments.

2021-03-24 10:20 UTC, Enmk commented on clickhouse/columns/itemview.cpp
> +        8,   /*DateTime64*/
agree, will fix

2021-03-24 10:33 UTC, Enmk commented on clickhouse/columns/decimal.cpp
> +    return absl::Int128High64(v) < 0;
yeah, this is quite a misleading name, will change that to `getSignBit`

2021-03-24 10:50 UTC, Enmk commented on clickhouse/types/types.h
> +using Int128 = absl::int128;
Several reasons, mostly for simplicity:
1. Simplify the interface. `ABSL_HAVE_INTRINSIC_INT128` is kind of internal-ish to `absl` and IMO it is not quite good idea to use it in the public API. Also using conditional type definition would void the abstraction of `absl::int128`: users would still have to learn about *both* `absl` and that special macro.
2. Simplify initialization of int128-literals and values from low64 and high64, with a helper method `absl::MakeInt128()`, which doesn't work well with raw `__int128`.

2021-03-24 13:40 UTC, traceon commented on clickhouse/types/types.h
> +using Int128 = absl::int128;
ok

2021-03-24 14:08 UTC, traceon approved these changes

2021-03-24 14:08 UTC, merged